package io.github.keddnyo.midoze.utils.devices

@Suppress("UNUSED_EXPRESSION")
class DeviceRepository {
    fun getDeviceNameByCode(deviceSource: Int, productionSource: Int): String {
        return when (deviceSource.toString()) {
            "30" -> "Amazfit Verge Lite Global"
            "56" -> "Zepp Z Chinese"
            "230" -> "Amazfit GTR3 Pro Global"
            "71" -> "Amazfit X Global"
            "50" -> "Amazfit T-Rex"
            "77" -> "Amazfit GTS2 Chinese"
            "57" -> "Zepp E Circle Chinese"
            "224" -> "Amazfit GTS3 Chinese"
            "64" -> "Amazfit GTR2 Global"
            "225" -> "Amazfit GTS3 Global"
            "78" -> "Amazfit GTS2 Global"
            "42" -> "Amazfit Bip Lite Global"
            "25" -> "Mi Band 4 Global"
            "61" -> "Zepp E Square Chinese"
            "226" -> "Amazfit GTR3 Chinese"
            "67" -> "Amazfit Pop Pro"
            "82" -> "Zepp E Square Global"
            "209" -> "Amazfit GTR2e Global"
            "37" -> "Amazfit GTR 42mm Chinese"
            "53" -> "Amazfit X Chinese"
            "36" -> "Amazfit GTR 47mm Global"
            "35" -> "Amazfit GTR 47mm Chinese"
            "31" -> "Mi Band 3i"
            "200" -> "Amazfit T-Rex Pro Global"
            "212" -> "Mi Band 6 Global"
            "24" -> "Mi Band 4 NFC"
            "73" -> "Amazfit Band 5"
            "69" -> "Amazfit Bip U Pro"
            "59" -> "Mi Band 5"
            "81" -> "Zepp E Circle Global"
            "44" -> "Amazfit GTR 42mm Lite Global"
            "206" -> "Amazfit GTR2e Chinese"
            "210" -> "Amazfit GTS2e Global"
            "211" -> "Mi Band 6 Chinese NFC"
            "68" -> "Amazfit Pop"
            "41" -> "Amazfit GTS Global"
            "207" -> "Amazfit GTS2e Chinese"
            "58" -> "Mi Band 5 NFC"
            "40" -> "Amazfit GTS Chinese"
            "51" -> "Amazfit GTR 42mm SWK"
            "20" -> "Amazfit Bip2"
            "12" -> "Amazfit Bip"
            "62" -> "Amazfit Neo"
            "70" -> "Amazfit Bip U"
            "76" -> "Zepp Z Global"
            "46" -> "Amazfit GTR 47mm Lite Global"
            "38" -> "Amazfit GTR 42mm Global"
            "227" -> "Amazfit GTR3 Global"
            "83" -> "Amazfit T-Rex Pro Chinese"
            "29" -> "Amazfit Bip S Lite"
            "28" -> "Amazfit Bip S"
            "229" -> "Amazfit GTR3 Pro Chinese"
            "92" -> "Amazfit GTS2 mini"
            "39" -> "Amazfit Bip Lite Chinese"
            "52" -> "Amazfit GTR 42mm SWK Global"
            "113" -> "Amazfit Bip"
            "63" -> "Amazfit GTR2 Chinese"
            else -> "Unknown $deviceSource $productionSource"
        }
    }
}